"""Physical four-dimensional Floquet quotient for planar periodic orbits.

After translation reduction the planar three-body problem is an 8D canonical
Hamiltonian system.  A regular strict periodic orbit still carries two commuting
continuous symmetries/first integrals relevant to the monodromy:

* time translation / energy, generated by ``X_H``;
* planar rotation / angular momentum, generated by ``X_L``.

At a regular point these generators span a two-dimensional isotropic subspace
``E``.  The physical transverse linear return map acts on the symplectic
quotient

    E^omega / E,

which has dimension four.  This module constructs a numerical representative
of that quotient without identifying the physical spectrum by deleting four
raw eigenvalues.

We choose the Euclidean-orthogonal complement of ``E`` inside ``E^omega`` as a
local representative ``W``.  The restricted symplectic form on ``W`` need not
be the standard matrix, but the induced 4x4 map must preserve it.  Eigenvalues,
trace invariants, event equations, and quotient eigendirections are independent
of the particular basis of ``W``.

Float64 results are screening/structural diagnostics.  Publication claims still
require the independent Julia BigFloat/canonical path.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .canonical_jacobi import (
    CanonicalFloquetResult,
    compute_canonical_floquet,
    full_to_jacobi,
    rhs,
    symplectic_matrix,
)

Array = np.ndarray


@dataclass(frozen=True)
class PhysicalFloquetResult:
    matrix: Array
    form: Array
    basis: Array
    multipliers: Array
    trace_a: float
    trace_b: float
    discriminant: float
    trace_roots: tuple[complex, complex]
    plus_one_event: float
    minus_one_event: float
    collision_event: float
    quotient_symplectic_defect: float
    quotient_leakage: float
    reciprocal_pairing_error: float
    neutral_isotropy_defect: float
    neutral_invariance_defect: float
    canonical: CanonicalFloquetResult

    def lift_vector(self, quotient_vector: Array) -> Array:
        """Lift quotient coordinates to an 8D canonical Jacobi tangent vector."""
        v = np.asarray(quotient_vector, dtype=complex)
        if v.shape != (4,):
            raise ValueError("quotient vector must have shape (4,)")
        return self.basis.astype(complex) @ v


def rotation_generator(state: Array) -> Array:
    """Hamiltonian vector field of total planar angular momentum in Jacobi coordinates."""
    z = np.asarray(state, dtype=float)
    if z.shape != (8,):
        raise ValueError("canonical Jacobi state must have shape (8,)")
    out = np.empty(8, dtype=float)
    for start in (0, 2, 4, 6):
        x, y = z[start : start + 2]
        out[start : start + 2] = (-y, x)
    return out


def _pairing_error(eigenvalues: Array) -> float:
    remaining = list(complex(x) for x in eigenvalues)
    worst = 0.0
    while remaining:
        lam = remaining.pop()
        if abs(lam) == 0.0 or not remaining:
            return float("inf")
        target = 1.0 / lam
        idx = min(range(len(remaining)), key=lambda i: abs(remaining[i] - target))
        mate = remaining.pop(idx)
        worst = max(worst, abs(mate - target))
    return float(worst)


def quotient_monodromy(
    monodromy: Array,
    flow_direction: Array,
    rotation_direction: Array,
    *,
    rank_tolerance: float = 2e-10,
) -> tuple[Array, Array, Array, float, float, float, float]:
    """Represent the induced map on ``E^omega/E`` in a local 4D basis.

    Returns ``(A, Omega, Q, symplectic_defect, leakage, isotropy_defect,
    neutral_invariance_defect)`` where columns of ``Q`` span the chosen
    representative of the quotient.
    """
    m = np.asarray(monodromy, dtype=float)
    if m.shape != (8, 8):
        raise ValueError("monodromy must have shape (8,8)")
    e = np.column_stack(
        (
            np.asarray(flow_direction, dtype=float),
            np.asarray(rotation_direction, dtype=float),
        )
    )
    if e.shape != (8, 2):
        raise ValueError("neutral generators must each have shape (8,)")
    norms = np.linalg.norm(e, axis=0)
    if np.any(norms == 0.0):
        raise ValueError("neutral generator has zero norm")
    e = e / norms
    neutral_singular = np.linalg.svd(e, compute_uv=False)
    if neutral_singular[-1] <= rank_tolerance:
        raise ValueError(
            "time and rotation generators are not independent; "
            "the regular 4D quotient is not valid on this symmetry stratum"
        )

    j = symplectic_matrix()
    isotropy = float(np.linalg.norm(e.T @ j @ e, ord=np.inf))

    # E^omega imposes E^T J v = 0.  Requiring Euclidean orthogonality to E
    # picks a unique local representative modulo E.  At a regular isotropic E
    # the four constraints are independent and leave a 4D space W.
    constraints = np.vstack((e.T @ j, e.T))
    _, singular, vh = np.linalg.svd(constraints, full_matrices=True)
    threshold = rank_tolerance * max(float(singular[0]), 1.0)
    rank = int(np.count_nonzero(singular > threshold))
    if rank != 4:
        raise ValueError(f"expected four independent quotient constraints, got rank {rank}")
    q = vh[rank:].T
    if q.shape != (8, 4):
        raise RuntimeError(f"unexpected quotient basis shape {q.shape}")

    omega = q.T @ j @ q
    form_singular = np.linalg.svd(omega, compute_uv=False)
    if form_singular[-1] <= rank_tolerance:
        raise ValueError("restricted quotient symplectic form is numerically degenerate")

    # Orthogonalize E only for leakage diagnostics. Q is already orthogonal to E.
    e_orth, _ = np.linalg.qr(e, mode="reduced")
    span = np.column_stack((e_orth, q))
    mapped = m @ q
    leakage = float(np.linalg.norm(mapped - span @ (span.T @ mapped), ord=np.inf))
    a = q.T @ mapped
    defect = float(np.linalg.norm(a.T @ omega @ a - omega, ord=np.inf))
    neutral_invariance = float(np.linalg.norm(m @ e - e, ord=np.inf))
    return a, omega, q, defect, leakage, isotropy, neutral_invariance


def physical_trace_invariants(
    matrix: Array,
) -> tuple[float, float, float, tuple[complex, complex]]:
    """Return the invariant coefficients of a physical 4x4 symplectic map.

    For characteristic polynomial

        lambda^4 - a lambda^3 + b lambda^2 - a lambda + 1,

    the reciprocal-pair trace roots ``t=lambda+1/lambda`` satisfy

        t^2 - a t + (b-2) = 0.
    """
    m = np.asarray(matrix, dtype=float)
    if m.shape != (4, 4):
        raise ValueError("physical Floquet matrix must have shape (4,4)")
    a = float(np.trace(m))
    b = float(0.5 * (a * a - np.trace(m @ m)))
    discriminant = float(a * a - 4.0 * b + 8.0)
    roots = np.roots(np.asarray([1.0, -a, b - 2.0], dtype=float))
    return a, b, discriminant, (complex(roots[0]), complex(roots[1]))


def compute_physical_floquet(
    full_state0: Array,
    masses: Array,
    period: float,
    *,
    rtol: float = 2e-11,
    atol: float = 2e-13,
) -> PhysicalFloquetResult:
    """Compute the canonical monodromy and its physical 4D symplectic quotient."""
    masses_array = np.asarray(masses, dtype=float)
    canonical = compute_canonical_floquet(
        full_state0,
        masses_array,
        period,
        rtol=rtol,
        atol=atol,
    )
    z0 = full_to_jacobi(full_state0, masses_array)
    flow = rhs(0.0, z0, masses_array)
    rotation = rotation_generator(z0)
    matrix, form, basis, defect, leakage, isotropy, neutral_invariance = quotient_monodromy(
        canonical.monodromy,
        flow,
        rotation,
    )
    multipliers = np.linalg.eigvals(matrix)
    a, b, discriminant, roots = physical_trace_invariants(matrix)
    plus = float(b - 2.0 * a + 2.0)
    minus = float(b + 2.0 * a + 2.0)
    collision = discriminant
    pairing = _pairing_error(multipliers)
    if not np.isfinite(pairing):
        raise RuntimeError("physical multiplier reciprocal pairing failed")
    return PhysicalFloquetResult(
        matrix=matrix,
        form=form,
        basis=basis,
        multipliers=multipliers,
        trace_a=a,
        trace_b=b,
        discriminant=discriminant,
        trace_roots=roots,
        plus_one_event=plus,
        minus_one_event=minus,
        collision_event=collision,
        quotient_symplectic_defect=defect,
        quotient_leakage=leakage,
        reciprocal_pairing_error=pairing,
        neutral_isotropy_defect=isotropy,
        neutral_invariance_defect=neutral_invariance,
        canonical=canonical,
    )


def physical_krein_form(result: PhysicalFloquetResult, eigenvector: Array) -> float:
    """Evaluate ``-i v* Omega v`` in quotient coordinates."""
    v = np.asarray(eigenvector, dtype=complex)
    if v.shape != (4,):
        raise ValueError("physical quotient eigenvector must have shape (4,)")
    value = -1j * np.vdot(v, result.form @ v)
    return float(np.real_if_close(value).real)
