#!/usr/bin/env python3
"""Emit the manuscript figure as TikZ, from committed artifacts only.

Standard library only, by design: the figure must be reproducible from this
repository without adding a plotting dependency, and its source must be
text-diffable so a reviewer can see exactly which points were drawn.

Panel (a) is the localized critical set in the mass plane, coloured by mechanism,
with the two unattached polyline ends marked.  Panel (b) is the universal Floquet
domain in the smooth invariants, whose walls are the exact polynomials of
src/threebody_atlas/bracket_criteria.py:18-20,

    G_plus = beta - 6 alpha + 20,  G_minus = beta - 2 alpha + 4,
    discriminant = (alpha - 4)^2 - 4 (beta - 4 alpha + 8),

together with the sheet's own probe images.  Nothing is fitted or interpolated:
every mark is a committed measurement, and the probe cloud is decimated by a
fixed stride that is printed into the caption data so the thinning is declared.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EV = ROOT / "research/evidence"
OUT = ROOT / "paper/short/fig_critical_graph.tex"

ROOTS = EV / "V1_COMBINED_CRITICAL_ROOTS_2026-08-17.json"
GRAPH = EV / "V1_CRITICAL_GRAPH.json"
AUDIT = EV / "V1_SIGN_TOPOLOGY_AUDIT_FULLDOMAIN_2026-08-18.json"

PROBE_STRIDE = 24  # declared in the caption; only thins panel (b)'s cloud
MARK = {"plus_one": "gplus", "minus_one": "gminus", "trace_collision": "delta"}


def load(p: Path):
    return json.loads(p.read_text(encoding="utf-8"))


def main() -> None:
    roots = load(ROOTS)["roots"]
    graph = load(GRAPH)
    audit = load(AUDIT)

    # panel (a): every localized root, by mechanism
    by_mode: dict[str, list[tuple[float, float]]] = {}
    for r in roots:
        if r.get("status") != "ok":
            continue
        m = r.get("event_mode")
        if m not in MARK:
            continue
        m1, m2 = float(r["masses"][0]), float(r["masses"][1])
        by_mode.setdefault(m, []).append((m1, m2))

    # the two ends the assembler leaves unattached, read from the graph itself
    unattached = []
    for e in graph["edges"]:
        for side in ("start", "end"):
            ep = e["endpoints"][side]
            if ep.get("node") is None:
                m = ep["masses"]
                unattached.append((e["id"], side, float(m[0]), float(m[1])))

    # panel (b): the sheet's converged probe images in (alpha, beta)
    cloud = [
        (float(p["alpha"]), float(p["beta"]))
        for i, p in enumerate(audit["probes"])
        if p.get("ok") and p.get("alpha") is not None and i % PROBE_STRIDE == 0
    ]

    L: list[str] = []
    add = L.append
    add("% GENERATED by scripts/plot_critical_graph_tikz.py -- do not edit by hand.")
    add("% Every mark below is a committed measurement; see that script's docstring.")
    add(r"\begin{figure}[t]\centering")
    add(r"\begin{tikzpicture}[x=13.5cm,y=5.4cm,line join=round]")
    # ---- panel (a) ----
    add(r"  \draw[gray!55] (0.8,0.7) rectangle (1.1,1.2);")
    add(r"  \node[anchor=north west,font=\scriptsize] at (0.8,1.2) {(a) mass plane};")
    for mode, pts in sorted(by_mode.items()):
        add(f"  % {mode}: {len(pts)} localized roots")
        add(f"  \\foreach \\x/\\y in {{{', '.join(f'{a:.6f}/{b:.6f}' for a, b in pts)}}}")
        add(f"    {{\\node[{MARK[mode]}] at (\\x,\\y) {{}};}}")
    for eid, side, m1, m2 in unattached:
        add(f"  \\node[unattached] at ({m1:.6f},{m2:.6f}) {{}};")
        add(f"  \\node[font=\\tiny,anchor=west] at ({m1 + 0.004:.6f},{m2:.6f}) "
            f"{{{eid.replace('_', chr(92) + '_')}:{side}}};")
    add(r"  \draw[->] (0.8,0.7) -- (1.115,0.7) node[right,font=\tiny] {$m_1$};")
    add(r"  \draw[->] (0.8,0.7) -- (0.8,1.215) node[above,font=\tiny] {$m_2$};")
    add(r"\end{tikzpicture}")
    add(r"\\[0.6em]")
    # ---- panel (b) ----
    amin, amax = -2.0, 10.0
    add(r"\begin{tikzpicture}[x=0.62cm,y=0.075cm,line join=round]")
    add(r"  \node[anchor=north west,font=\scriptsize] at (-2,32) {(b) universal Floquet domain};")
    add(f"  \\draw[wall] ({amin},{6*amin-20:.3f}) -- ({amax},{6*amax-20:.3f})"
        r" node[right,font=\tiny] {$G_+=0$};")
    add(f"  \\draw[wall] ({amin},{2*amin-4:.3f}) -- ({amax},{2*amax-4:.3f})"
        r" node[right,font=\tiny] {$G_-=0$};")
    para = " ".join(
        f"({a:.3f},{((a - 4.0) ** 2) / 4.0 + 4.0 * a - 8.0:.3f})"
        for a in [amin + i * (amax - amin) / 120.0 for i in range(121)]
    )
    add(r"  \draw[wall,dashed] plot coordinates {" + para + r"}"
        r" node[right,font=\tiny] {$\Delta=0$};")
    add(f"  % sheet probe images, stride {PROBE_STRIDE} of "
        f"{sum(1 for p in audit['probes'] if p.get('ok') and p.get('alpha') is not None)}")
    for a, b in cloud:
        if amin <= a <= amax and -12.0 <= b <= 32.0:
            add(f"  \\node[sheet] at ({a:.4f},{b:.4f}) {{}};")
    for a, b, lab in ((0, -4, "(0,-4)"), (4, 4, "(4,4)"), (8, 28, "(8,28)")):
        add(f"  \\node[vertex] at ({a},{b}) {{}};")
        add(f"  \\node[font=\\tiny,anchor=south west] at ({a},{b}) {{{lab}}};")
    add(r"  \draw[->] (-2,-12) -- (10.4,-12) node[right,font=\tiny] {$\alpha$};")
    add(r"  \draw[->] (-2,-12) -- (-2,33) node[above,font=\tiny] {$\beta$};")
    add(r"\end{tikzpicture}")
    n_a = sum(len(v) for v in by_mode.values())
    add(r"\caption{\label{fig:graph}(a) All $" + str(n_a) + r"$ localized critical roots in the "
        r"declared mass rectangle, by mechanism: $G_+$ crossings, $G_-$ crossings and $\Delta$ "
        r"collisions. Open circles are the two polyline ends the assembler leaves unattached. "
        r"(b) The universal Floquet domain in the smooth invariants, with the exact walls "
        r"$G_+=\beta-6\alpha+20$, $G_-=\beta-2\alpha+4$ and "
        r"$\Delta=(\alpha-4)^2-4(\beta-4\alpha+8)$, their three exact vertices, and the sheet's "
        r"converged probe images (every " + str(PROBE_STRIDE) + r"th of "
        + str(sum(1 for p in audit["probes"] if p.get("ok") and p.get("alpha") is not None))
        + r", thinned only for legibility). Every mark is a committed measurement; nothing is "
        r"fitted or interpolated.}")
    add(r"\end{figure}")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {n_a} roots, {len(unattached)} unattached ends, "
          f"{len(cloud)} probe marks")


if __name__ == "__main__":
    main()
