#!/usr/bin/env python3
"""Emit the manuscript figure as TikZ, from committed artifacts only.

Standard library only, by design: the figure must be reproducible from this
repository without adding a plotting dependency, and its source must be
text-diffable so a reviewer can see exactly which points were drawn.

Panel (a) is the localized critical set in the mass plane, coloured by mechanism,
with the two unattached polyline ends marked.  Panel (b) is the universal Floquet
domain in the smooth invariants, whose walls are the exact polynomials of
src/threebody_atlas/bracket_criteria.py:18-20,

    G_plus = beta - 6 alpha + 20,  G_minus = beta - 2 alpha + 4,
    discriminant = (alpha - 4)^2 - 4 (beta - 4 alpha + 8),

together with the sheet's own probe images.  Nothing is fitted or interpolated:
every mark is a committed measurement, and the probe cloud is decimated by a
fixed stride that is printed into the caption data so the thinning is declared.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EV = ROOT / "research/evidence"
OUT = ROOT / "paper/short/fig_critical_graph.tex"

ROOTS = EV / "V1_COMBINED_CRITICAL_ROOTS_2026-08-17.json"
GRAPH = EV / "V1_CRITICAL_GRAPH.json"
AUDIT = EV / "V1_SIGN_TOPOLOGY_AUDIT_FULLDOMAIN_2026-08-18.json"

PROBE_STRIDE = 24  # declared in the caption; only thins panel (b)'s cloud
MARK = {"plus_one": "gplus", "minus_one": "gminus", "trace_collision": "delta"}


def load(p: Path):
    return json.loads(p.read_text(encoding="utf-8"))


def main() -> None:
    roots = load(ROOTS)["roots"]
    graph = load(GRAPH)
    audit = load(AUDIT)

    # panel (a): every localized root, by mechanism
    by_mode: dict[str, list[tuple[float, float]]] = {}
    for r in roots:
        if r.get("status") != "ok":
            continue
        m = r.get("event_mode")
        if m not in MARK:
            continue
        m1, m2 = float(r["masses"][0]), float(r["masses"][1])
        by_mode.setdefault(m, []).append((m1, m2))

    # the two ends the assembler leaves unattached, read from the graph itself
    unattached = []
    for e in graph["edges"]:
        for side in ("start", "end"):
            ep = e["endpoints"][side]
            if ep.get("node") is None:
                m = ep["masses"]
                unattached.append((e["id"], side, float(m[0]), float(m[1])))

    # panel (b): the sheet's converged probe images in (alpha, beta)
    cloud = [
        (float(p["alpha"]), float(p["beta"]))
        for i, p in enumerate(audit["probes"])
        if p.get("ok") and p.get("alpha") is not None and i % PROBE_STRIDE == 0
    ]

    L: list[str] = []
    add = L.append
    n_probe = sum(1 for q in audit["probes"] if q.get("ok") and q.get("alpha") is not None)
    add("% GENERATED by scripts/plot_critical_graph_tikz.py -- do not edit by hand.")
    add("% Every mark below is a committed measurement; see that script's docstring.")
    add(r"\begin{figure*}[t]\centering")

    # ---------------- panel (a): mass plane ----------------
    # 0.3 x 0.5 in mass units drawn 6.2cm x 6.0cm, clipped so nothing escapes the box
    add(r"\begin{subfigure}{0.47\textwidth}\centering")
    add(r"\begin{tikzpicture}[x=20.7cm,y=12.0cm,line join=round]")
    add(r"  \begin{scope}")
    add(r"    \clip (0.8,0.7) rectangle (1.1,1.2);")
    for mode, pts in sorted(by_mode.items()):
        add(f"    % {mode}: {len(pts)} localized roots")
        add(f"    \\foreach \\x/\\y in {{{', '.join(f'{a:.6f}/{b:.6f}' for a, b in pts)}}}")
        add(f"      {{\\node[{MARK[mode]}] at (\\x,\\y) {{}};}}")
    for i, (_eid, _side, m1, m2) in enumerate(unattached, start=1):
        add(f"    \\node[unattached,label={{[font=\\scriptsize,label distance=-1pt]"
            f"{'below right' if i == 1 else 'above left'}:E{i}}}] at ({m1:.6f},{m2:.6f}) {{}};")
    add(r"  \end{scope}")
    add(r"  \draw[gray!70] (0.8,0.7) rectangle (1.1,1.2);")
    add(r"  \foreach \v in {0.8,0.9,1.0,1.1}")
    add(r"    {\draw (\v,0.7) -- ++(0,0.008) node[below=3pt,font=\scriptsize] {$\v$};}")
    add(r"  \foreach \v in {0.7,0.8,0.9,1.0,1.1,1.2}")
    add(r"    {\draw (0.8,\v) -- ++(0.0022,0) node[left=3pt,font=\scriptsize] {$\v$};}")
    add(r"  \node[font=\scriptsize,anchor=north] at (0.95,0.688) {$m_1$};")
    add(r"  \node[font=\scriptsize,rotate=90,anchor=south] at (0.7885,0.95) {$m_2$};")
    add(r"\end{tikzpicture}")
    add(r"\caption{}\label{fig:mass}")
    add(r"\end{subfigure}\hfill")

    # ---------------- panel (b): universal Floquet domain ----------------
    amin, amax, bmin, bmax = -2.0, 10.0, -12.0, 32.0
    add(r"\begin{subfigure}{0.47\textwidth}\centering")
    add(r"\begin{tikzpicture}[x=0.50cm,y=0.1364cm,line join=round]")
    add(r"  \begin{scope}")
    add(f"    \\clip ({amin},{bmin}) rectangle ({amax},{bmax});")
    for a, b in cloud:
        add(f"    \\node[sheet] at ({a:.4f},{b:.4f}) {{}};")
    add(f"    \\draw[wall] ({amin},{6*amin-20:.3f}) -- ({amax},{6*amax-20:.3f});")
    add(f"    \\draw[wall] ({amin},{2*amin-4:.3f}) -- ({amax},{2*amax-4:.3f});")
    para = " ".join(
        f"({a:.3f},{((a - 4.0) ** 2) / 4.0 + 4.0 * a - 8.0:.3f})"
        for a in [amin + i * (amax - amin) / 160.0 for i in range(161)]
    )
    add(r"    \draw[wall,dashed] plot coordinates {" + para + r"};")
    add(r"  \end{scope}")
    add(r"  \draw[gray!70] " + f"({amin},{bmin}) rectangle ({amax},{bmax});")
    for a, b, lab, pos in ((0, -4, "(0,-4)", "below right"), (4, 4, "(4,4)", "above left"),
                           (8, 28, "(8,28)", "left")):
        add(f"  \\node[vertex,label={{[font=\\scriptsize,label distance=-1pt]{pos}:{lab}}}] "
            f"at ({a},{b}) {{}};")
    add(r"  \node[font=\scriptsize,anchor=west] at (7.0,-9.2) {$G_+\!=\!0$};")
    add(r"  \node[font=\scriptsize,anchor=west] at (7.0,17.0) {$G_-\!=\!0$};")
    add(r"  \node[font=\scriptsize,anchor=east] at (2.6,20.0) {$\Delta\!=\!0$};")
    add(r"  \foreach \v in {-2,0,2,4,6,8,10}")
    add(f"    {{\\draw (\\v,{bmin}) -- ++(0,0.7) node[below=3pt,font=\\scriptsize] {{$\\v$}};}}")
    add(r"  \foreach \v in {-12,0,12,24}")
    add(f"    {{\\draw ({amin},\\v) -- ++(0.14,0) node[left=3pt,font=\\scriptsize] {{$\\v$}};}}")
    add(f"  \\node[font=\\scriptsize,anchor=north] at (4,{bmin - 3.4:.1f}) {{$\\alpha$}};")
    add(f"  \\node[font=\\scriptsize,rotate=90,anchor=south] at ({amin - 1.15:.2f},10) {{$\\beta$}};")
    add(r"\end{tikzpicture}")
    add(r"\caption{}\label{fig:domain}")
    add(r"\end{subfigure}")

    # ---------------- legend + caption ----------------
    add(r"\\[0.4em]{\footnotesize")
    add(r"\tikz[baseline=-0.5ex]{\node[gplus]{};}~$G_+$ crossing \quad")
    add(r"\tikz[baseline=-0.5ex]{\node[gminus]{};}~$G_-$ crossing \quad")
    add(r"\tikz[baseline=-0.5ex]{\node[delta]{};}~$\Delta$ collision \quad")
    add(r"\tikz[baseline=-0.5ex]{\node[unattached]{};}~unattached end \quad")
    add(r"\tikz[baseline=-0.5ex]{\node[vertex]{};}~exact vertex}")
    n_a = sum(len(v) for v in by_mode.values())
    e1, e2 = unattached[0], unattached[1]
    add(r"\caption{\label{fig:graph}Left: all $" + str(n_a) + r"$ localized critical roots in the "
        r"declared mass rectangle $m_1\in[0.8,1.1]$, $m_2\in[0.7,1.2]$ at $m_3=1$, by mechanism. "
        r"E1 and E2 are the two polyline ends the assembler leaves unattached, "
        + f"\\texttt{{{e1[0].replace('_', chr(92) + '_')}}} start at "
          f"$({e1[2]:.3f},{e1[3]:.7f})$ and "
          f"\\texttt{{{e2[0].replace('_', chr(92) + '_')}}} end at "
          f"$({e2[2]:.3f},{e2[3]:.7f})$. "
        r"Right: the universal Floquet domain in the smooth invariants, with the exact walls "
        r"$G_+=\beta-6\alpha+20$, $G_-=\beta-2\alpha+4$ and "
        r"$\Delta=(\alpha-4)^2-4(\beta-4\alpha+8)$, their three exact vertices, and the sheet's "
        r"converged probe images (every " + str(PROBE_STRIDE) + r"th of " + str(n_probe)
        + r", thinned for legibility only). Both panels are clipped to the axes shown. Every mark is "
        r"a committed measurement; nothing is fitted or interpolated.}")
    add(r"\end{figure*}")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {n_a} roots, {len(unattached)} unattached ends, "
          f"{len(cloud)} probe marks")


if __name__ == "__main__":
    main()
